name: "test"
on:
  push:
    branches:
      - master

jobs:
  run-test:
    strategy:
      matrix:
        node: [10.x, 12.x]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node version
      uses: actions/setup-node@master
      with:
        version: ${{ matrix.node }}

    - name: "npm ci"
      run: npm ci

    - name: "npm test"
      run: npm test
